version: '3.6'
services:
    db:
        image: mariadb
        restart: always
        container_name: mysql-libservices
        # values for environment are in a .env file 
        environment:
          - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
          - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
          - MYSQL_USER=${MYSQL_DATABASE_USER}
          - MYSQL_PASSWORD=${MYSQL_DATABASE_PASSWORD}
        ports:
          - "${DATABASE_PORT}:3306"
        volumes:
#          - db-mysql-data:/var/lib/mysql/data
          - ./init:/docker-entrypoint-initdb.d
    
